"""empty message

Revision ID: 45f283168c43
Revises: 53569ee3a976
Create Date: 2021-09-03 20:28:51.194014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f283168c43'
down_revision = '53569ee3a976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_title', sa.String(length=100), nullable=False),
    sa.Column('book_reference', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(length=5000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_post_timestamp'), 'blog_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_post_timestamp'), table_name='blog_post')
    op.drop_table('blog_post')
    # ### end Alembic commands ###
