"""empty message

Revision ID: 53569ee3a976
Revises: 628ea96ef571
Create Date: 2021-09-01 23:18:43.115642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53569ee3a976'
down_revision = '628ea96ef571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'book', type_='unique')
    # ### end Alembic commands ###
