"""empty message

Revision ID: 7189f1c6fc9d
Revises: 45f283168c43
Create Date: 2021-09-03 21:39:38.449807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7189f1c6fc9d'
down_revision = '45f283168c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_author_key', 'book', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('book_author_key', 'book', ['author'])
    # ### end Alembic commands ###
