"""empty message

Revision ID: 73e0f024b69c
Revises: a046df251115
Create Date: 2021-09-03 22:21:53.940151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e0f024b69c'
down_revision = 'a046df251115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'book_reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('book_reference', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
