"""empty message

Revision ID: 8af77162423c
Revises: 1b2bda8b1271
Create Date: 2021-09-03 21:47:41.261451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af77162423c'
down_revision = '1b2bda8b1271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('user_token', sa.String(), nullable=False))
    op.drop_constraint('blog_post_user_id_fkey', 'blog_post', type_='foreignkey')
    op.create_foreign_key(None, 'blog_post', 'user', ['user_token'], ['token'])
    op.drop_column('blog_post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blog_post', type_='foreignkey')
    op.create_foreign_key('blog_post_user_id_fkey', 'blog_post', 'user', ['user_id'], ['id'])
    op.drop_column('blog_post', 'user_token')
    # ### end Alembic commands ###
