"""empty message

Revision ID: a046df251115
Revises: 8af77162423c
Create Date: 2021-09-03 21:48:49.509838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a046df251115'
down_revision = '8af77162423c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('user_id', sa.String(), nullable=False))
    op.drop_constraint('blog_post_user_token_fkey', 'blog_post', type_='foreignkey')
    op.create_foreign_key(None, 'blog_post', 'user', ['user_id'], ['id'])
    op.drop_column('blog_post', 'user_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blog_post', type_='foreignkey')
    op.create_foreign_key('blog_post_user_token_fkey', 'blog_post', 'user', ['user_token'], ['token'])
    op.drop_column('blog_post', 'user_id')
    # ### end Alembic commands ###
