"""empty message

Revision ID: c5263ef803b8
Revises: f3f3e1e428ea
Create Date: 2021-09-08 16:26:22.025867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5263ef803b8'
down_revision = 'f3f3e1e428ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'book', type_='unique')
    # ### end Alembic commands ###
